name: just_audio
description: A feature-rich audio player for Flutter. Loop, clip and sequence any sound from any source (asset/file/URL/stream) in gapless playlists.
version: 0.10.4
repository: https://github.com/ryanheise/just_audio/tree/minor/just_audio
issue_tracker: https://github.com/ryanheise/just_audio/issues
topics:
  - audio
  - sound
  - player
  - background

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

dependencies:
  just_audio_platform_interface: ^4.5.0
  # just_audio_platform_interface:
  #   path: ../just_audio_platform_interface
  just_audio_web: ^0.4.15
  # just_audio_web:
  #   path: ../just_audio_web
  audio_session: 
    git:
      url: "https://gitcode.com/openharmony-sig/flutter_audio_session.git"
      path: ""
  rxdart: '>=0.26.0 <0.29.0'
  path: ^1.8.0
  path_provider: 
    git:
      url: "https://gitcode.com/openharmony-sig/flutter_packages.git"
      path: "packages/path_provider/path_provider"
  async: ^2.5.0
  uuid: '>=3.0.1 <5.0.0'
  crypto: ^3.0.0
  meta: ^1.3.0
  flutter:
    sdk: flutter
  synchronized: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  plugin_platform_interface: ^2.0.0
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.ryanheise.just_audio
        pluginClass: JustAudioPlugin
      ios:
        pluginClass: JustAudioPlugin
        sharedDarwinSource: true
      macos:
        pluginClass: JustAudioPlugin
        sharedDarwinSource: true
      web:
        default_package: just_audio_web
      ohos:
        pluginClass: JustAudioOhosPlugin
