name: just_audio_example
description: Demonstrates how to use the just_audio plugin.
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  audio_session: 
    git:
      url: "https://gitcode.com/openharmony-sig/flutter_audio_session.git"
      path: ""
  rxdart: '>=0.26.0 <0.29.0'
  just_audio_media_kit: ^2.1.0
  media_kit_libs_linux: any
  media_kit_libs_windows_audio: any
  # Other platform implementations below:
  # just_audio_windows: ^0.2.0
  # just_audio_libwinmedia: ^0.0.4
  just_audio:
    path: ../

# Uncomment when testing platform interface changes.
# dependency_overrides:
#   just_audio_platform_interface:
#     path: ../../just_audio_platform_interface
#   just_audio_web:
#     path: ../../just_audio_web

dev_dependencies:
  # TODO: uncomment these dependencies when they have nullsafe versions.
  # flutter_driver:
  #   sdk: flutter
  flutter_test:
    sdk: flutter
  # integration_test: ^1.0.1
  test: ^1.16.4
  flutter_lints: ^2.0.1

flutter:
  # disable-swift-package-manager: true
  uses-material-design: true

  assets:
    - audio/
